version: '2'

services:
  gulag-workshop:
    container_name: gulag-workshop
    image: gitlab.urbica.co:5001/device25/gulag-workshop:master
    restart: always
    environment:
      - .env
    ports:
      - 3001:3001

networks:
  default:
    external:
      name: production-network
